## sklearn.model_selection.GridSearchCV
* class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)

In [1]:
# refit=True: 제일 좋은걸 저장
# 격자 전체를 crossvalidation을 통해서 학습

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [14]:
from sklearn.model_selection import train_test_split
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier(random_state=12)
parameters = {'max_depth': [1,2,3], 'min_samples_split':[2,3]}

In [15]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv = 3)
grid_dtree.fit(X_train, y_train)

print(grid_dtree.best_estimator_)
print(grid_dtree.best_params_)

DecisionTreeClassifier(max_depth=3, random_state=12)
{'max_depth': 3, 'min_samples_split': 2}


In [16]:
pd.DataFrame(grid_dtree.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.002334      0.000471         0.001332    4.711456e-04   
1       0.001998      0.000816         0.000665    4.704732e-04   
2       0.002664      0.000942         0.000333    4.709208e-04   
3       0.001997      0.000817         0.001001    5.947204e-07   
4       0.004331      0.001248         0.002332    1.245578e-03   
5       0.003663      0.001697         0.000666    4.707522e-04   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [17]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [18]:
iris.target[0]

0

In [19]:
import numpy as np
X = np.array([5.2, 3.3, 1.7, 0.3]).reshape(1,-1)
grid_dtree.predict(X)

array([0])

In [20]:
dtree = grid_dtree.best_estimator_

In [21]:
y_test

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
pred = dtree.predict(X_test)
print(accuracy_score(y_test,pred))

0.9666666666666667


In [24]:
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])