In [1]:
from tensorflow.keras.datasets import mnist

mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt

batch_size=128
num_classes=10
epochs=20
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [3]:
x_train = x_train.reshape(60000,784)
x_test = x_test.reshape(10000,784)
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train/=255
x_test/=255
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [5]:
# one hot encoding 같은
y_train= tf.keras.utils.to_categorical(y_train,num_classes)
y_test= tf.keras.utils.to_categorical(y_test,num_classes)

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(512,activation='relu',input_shape=(784,)))
model.add(tf.keras.layers.Dense(num_classes,activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [6]:
sgd= tf.keras.optimizers.SGD(lr=0.1)

model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

history= model.fit(x_train,y_train,
                   batch_size=batch_size,
                   epochs=epochs)

score= model.evaluate(x_test,y_test,verbose=0)
print('테스트 손실값:',score[0])
print('테스트 정확도:',score[1])

c:\Pythontemp\lib\site-packages\keras\optimizers\optimizer_v2\gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/20
469/469 [==============================] - 9s 15ms/step - loss: 0.4427 - accuracy: 0.8831
Epoch 2/20
469/469 [==============================] - 6s 12ms/step - loss: 0.2444 - accuracy: 0.9309
Epoch 3/20
469/469 [==============================] - 6s 12ms/step - loss: 0.1939 - accuracy: 0.9458
Epoch 4/20
469/469 [==============================] - 5s 12ms/step - loss: 0.1612 - accuracy: 0.9550
Epoch 5/20
469/469 [==============================] - 6s 13ms/step - loss: 0.1385 - accuracy: 0.9617
Epoch 6/20
469/469 [==============================] - 6s 12ms/step - loss: 0.1215 - accuracy: 0.9663
Epoch 7/20
469/469 [==============================] - 5s 12ms/step - loss: 0.1081 - accuracy: 0.9701
Epoch 8/20
469/469 [==============================] - 6s 12ms/step - loss: 0.0970 - accuracy: 0.9735
Epoch 9/20
469/469 [==============================] - 6s 12ms/step - loss: 0.0881 - accuracy: 0.9761
Epoch 10/20
469/469 [==============================] - 6s 12ms/step - loss: 0.0800 - accura

In [8]:
model.predict(x_test)

313/313 [==============================] - 3s 7ms/step


array([[3.5181217e-06, 1.6180552e-07, 1.8521069e-04, ..., 9.9932170e-01,
        9.5284613e-06, 2.9795150e-05],
       [6.2706513e-06, 2.2776712e-04, 9.9812406e-01, ..., 1.1249241e-10,
        2.8919737e-04, 2.9670592e-11],
       [1.9913943e-05, 9.9591196e-01, 8.3821651e-04, ..., 1.3217604e-03,
        1.0228287e-03, 4.2782809e-05],
       ...,
       [9.6291277e-09, 1.8367594e-09, 2.9451319e-09, ..., 1.0924950e-05,
        4.3594031e-05, 5.7650577e-05],
       [9.2279458e-07, 1.9562938e-07, 2.9043900e-08, ..., 6.4545823e-08,
        2.9453603e-04, 3.0105177e-08],
       [3.5214674e-07, 2.6494014e-09, 2.2980235e-07, ..., 2.7391193e-12,
        1.1035215e-08, 7.1960904e-10]], dtype=float32)

In [9]:
model.predict(x_test)[0] # 제일 높은 거 9.9932170e-01로 7로 예측

313/313 [==============================] - 2s 7ms/step


array([3.5181217e-06, 1.6180552e-07, 1.8521069e-04, 4.4446072e-04,
       3.8488370e-08, 5.5122632e-06, 8.0563395e-10, 9.9932170e-01,
       9.5284613e-06, 2.9795150e-05], dtype=float32)

In [10]:
y_test[0] # 실제로 7

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)