In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("../datasets/tmdb_5000_movies.csv")
df

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [60]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [61]:
df['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [62]:
df['genres'][0] # 문자열. a = "['호랑이', '사자', '기린']"

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [63]:
from ast import literal_eval
df['genres']= df['genres'].apply(literal_eval)

In [64]:
df['genres'][0] # 리스트 딕셔너리 형태

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [65]:
# df['genres'] = df['genres'].apply(literal_eval)
df['keywords'] = df['keywords'].apply(literal_eval)

df['genres'] = df['genres'].apply(lambda x : [y['name'] for y in x])
df['keywords'] = df['keywords'].apply(lambda x : [y['name'] for y in x])
df[['genres', 'keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

df['genres_literal'] = df['genres'].apply(lambda x:(' ').join(x))
df['genres_literal'][:1]

0    Action Adventure Fantasy Science Fiction
Name: genres_literal, dtype: object

In [67]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


min_df float 범위 [0.0, 1.0] 또는 int, 기본값=1
어휘를 구축할 때 문서 빈도가 주어진 임계값보다 엄격하게 낮은 용어는 무시하십시오. 이 값은 문헌에서 컷오프라고도 합니다. 

(1, 2) means unigrams and bigrams  Only applies if analyzer is not callable.

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:3])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]]


In [69]:
genre_sim.argsort() # 값이 낮은 순으로 값의 인덱스 값 나옴

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [70]:
print(genre_sim[1][262])

0.9999999999999999


In [71]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]  # 값이 큰 순으로 값의 인덱스 값 나옴
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [72]:
genre_sim_sorted_ind[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]], dtype=int64)

In [73]:
genre_sim_sorted_ind[1:2]

array([[ 262,    1,  129, ..., 3069, 3067, 2401]], dtype=int64)

In [74]:
df[df['title'] == 'The Godfather']

budget          genres                      homepage   id  \
3337  6000000  [Drama, Crime]  http://www.thegodfather.com/  238   

                                               keywords original_language  \
3337  [italy, love at first sight, loss of father, p...                en   

     original_title                                           overview  \
3337  The Godfather  Spanning the years 1945 to 1955, a chronicle o...   

      popularity                               production_companies  ...  \
3337  143.659698  [{"name": "Paramount Pictures", "id": 4}, {"na...  ...   

     release_date    revenue  runtime  \
3337   1972-03-14  245066411    175.0   

                                       spoken_languages    status  \
3337  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                         tagline          title vote_average  vote_count  \
3337  An offer you can't refuse.  The Godfather          8.4        5893   

      genres_literal  
3337     Drama Crime  

[1 rows x 21 columns]

In [75]:
df[df['title'] == 'The Godfather'].index.values

array([3337], dtype=int64)

In [76]:
genre_sim_sorted_ind[3337,:10]

array([2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866],
      dtype=int64)

In [77]:
def find_sim_movie(df, sorted_ind, title_name, top_n = 10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    # print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    print(similar_indexes)
    return df.iloc[similar_indexes]

In [78]:
similar_movies = find_sim_movie(df, genre_sim_sorted_ind, 'The Godfather', 10)

[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]


In [79]:
similar_movies[['title', 'vote_average']]

title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [80]:
C = df['vote_average'].mean()
m = df['vote_count'].quantile(0.6)

In [81]:
print('C:', round(C,3), 'm:', round(m,3))

C: 6.092 m: 370.2


In [82]:
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    return (((v/(v+m)) * R) + ((m/(m+v)) * C))

In [83]:
df['weighted_vote'] = df.apply(weighted_vote_average, axis=1)

In [84]:
def find_sim_movie_ver2(df, sorted_ind, title_name, top_n = 10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    # print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    print(similar_indexes)
    similar_indexes = similar_indexes[similar_indexes != title_index]
    print(similar_indexes)
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

In [85]:
similar_movies = find_sim_movie_ver2(df, genre_sim_sorted_ind, 'The Godfather', 10)

[2731 1243 3636 1946 2640 4065 1847 4217  883 3866 3112 4041  588 3337
 3378  281 1663 1464 1149 2839]
[2731 1243 3636 1946 2640 4065 1847 4217  883 3866 3112 4041  588 3378
  281 1663 1464 1149 2839]


In [86]:
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  weighted_vote  \
2731       The Godfather: Part II           8.3       8.079586   
1847                   GoodFellas           8.2       7.976937   
3866                  City of God           8.1       7.759693   
1663  Once Upon a Time in America           8.2       7.657811   
883           Catch Me If You Can           7.7       7.557097   
281             American Gangster           7.4       7.141396   
4041              This Is England           7.4       6.739664   
1149              American Hustle           6.8       6.717525   
1243                 Mean Streets           7.2       6.626569   
2839                     Rounders           6.9       6.530427   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1847  [Drama, Crime]        3128  
3866  [Drama, Crime]        1814  
1663  [Drama, Crime]        1069  
883   [Drama, Crime]        3795  
281   [Drama, Crime]        1502  
4041  [Drama, Crime]         363  
1149  [Drama, Crime]        2807  
1243  [Drama, Crime]         345  
2839  [Drama, Crime]         439