#### Library Import

In [19]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

#### Data Import

In [20]:
ratings = pd.read_csv('../datasets/ratings_small.csv')

ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [21]:
movies = pd.read_csv('../datasets/movies_small.csv')

movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [22]:
# ratings 와 movies merge

df = pd.merge(ratings, movies , on='movieId', how='inner')
df.head()

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy

In [23]:
matrix = df.pivot_table(index='userId', columns='title', values='rating').fillna(0)
matrix.head()

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              0.0                                      0.0   
2              0.0                                      0.0   
3              0.0                                      0.0   
4              0.0                                      0.0   
5              0.0                                      0.0   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          0.0                  0.0   
2                          0.0                  0.0   
3                          0.0                  0.0   
4                          0.0                  0.0   
5                          0.0                  0.0   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             0.0                              0.0   
2                             0.0                              0.0   
3                             0.0                              0.0   
4                             0.0                              0.0   
5                             0.0                              0.0   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      0.0                   0.0                          0.0   
2                      0.0                   0.0                          0.0   
3                      0.0                   0.0                          0.0   
4                      0.0                   0.0                          0.0   
5                      0.0                   0.0                          0.0   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  0.0  ...          0.0           0.0   
2                                  0.0  ...          0.0           0.0   
3                                  0.0  ...          0.0           0.0   
4                                  0.0  ...          0.0           0.0   
5                                  0.0  ...          0.0           0.0   

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId                                           
1                 0.0                      0.0   
2                 0.0                      0.0   
3                 0.0                      0.0   
4                 0.0                      0.0   
5                 0.0                      0.0   

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId                                                           
1                                                     0.0        
2                                                     0.0        
3                                                     0.0        
4                                                     0.0        
5                                                     0.0        

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1                   0.0         0.0                             0.0   
2                   0.0         0.0                             0.0   
3                   0.0         0.0                             0.0   
4                   0.0         0.0                             0.0   
5                   0.0         0.0                             0.0   

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
userId                                                                    
1                         4.0                                        0.0  
2                         0.0                            

In [24]:
moving_user_rating = matrix.values.T
moving_user_rating

array([[0. , 0. , 0. , ..., 0. , 0. , 4. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 1.5],
       [4. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

# sklearn.decomposition.TruncatedSVD
- class sklearn.decomposition.TruncatedSVD(n_components=2, *, algorithm='randomized', n_iter=5, n_oversamples=10, power_iteration_normalizer='auto', random_state=None, tol=0.0)

In [25]:
SVD = TruncatedSVD(n_components=12, n_iter=7, random_state=42) #n_components: 차원
svd_matrix = SVD.fit_transform(moving_user_rating)
svd_matrix.shape # userId 12개로

(9719, 12)

In [26]:
item_similiarity = np.corrcoef(svd_matrix)
item_similiarity.shape

(9719, 9719)

In [27]:
movie_title = matrix.columns
movie_title_list = list(movie_title)

In [28]:
coffey_hands = movie_title_list.index("Guardians of the Galaxy (2014)")
coffey_hands

3667

In [29]:
item_similiarity[coffey_hands]

array([ 0.4790324 ,  0.09670657,  0.13596476, ...,  0.31948757,
        0.28132989, -0.03376383])

In [30]:
list(movie_title[coffey_hands >= 0.9])[:10]

[array(["'71 (2014)", "'Hellboy': The Seeds of Creation (2004)",
        "'Round Midnight (1986)", ..., 'xXx: State of the Union (2005)',
        '¡Three Amigos! (1986)',
        'À nous la liberté (Freedom for Us) (1931)'], dtype=object)]

#### 특정 사용자에게 추천해주기

In [31]:
matrix_1 = matrix.to_numpy()

In [32]:
matrix_1_mean = np.mean(matrix_1, axis=1)
matrix_norm = matrix_1 - matrix_1_mean.reshape(-1,1)
matrix_norm

array([[-0.10422883, -0.10422883, -0.10422883, ..., -0.10422883,
         3.89577117, -0.10422883],
       [-0.01178105, -0.01178105, -0.01178105, ..., -0.01178105,
        -0.01178105, -0.01178105],
       [-0.00977467, -0.00977467, -0.00977467, ..., -0.00977467,
        -0.00977467, -0.00977467],
       ...,
       [-0.26798024, -0.26798024, -0.26798024, ..., -0.26798024,
        -0.26798024, -0.26798024],
       [-0.01244984, -0.01244984, -0.01244984, ..., -0.01244984,
        -0.01244984, -0.01244984],
       [ 3.5058648 , -0.4941352 , -0.4941352 , ...,  1.0058648 ,
        -0.4941352 , -0.4941352 ]])

In [33]:
pd.DataFrame(matrix_norm, columns=matrix.columns).head()

title  '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
0       -0.104229                                -0.104229   
1       -0.011781                                -0.011781   
2       -0.009775                                -0.009775   
3       -0.079020                                -0.079020   
4       -0.016463                                -0.016463   

title  'Round Midnight (1986)  'Salem's Lot (2004)  'Til There Was You (1997)  \
0                   -0.104229            -0.104229                  -0.104229   
1                   -0.011781            -0.011781                  -0.011781   
2                   -0.009775            -0.009775                  -0.009775   
3                   -0.079020            -0.079020                  -0.079020   
4                   -0.016463            -0.016463                  -0.016463   

title  'Tis the Season for Love (2015)  'burbs, The (1989)  \
0                            -0.104229           -0.104229   
1                            -0.011781           -0.011781   
2                            -0.009775           -0.009775   
3                            -0.079020           -0.079020   
4                            -0.016463           -0.016463   

title  'night Mother (1986)  (500) Days of Summer (2009)  \
0                 -0.104229                    -0.104229   
1                 -0.011781                    -0.011781   
2                 -0.009775                    -0.009775   
3                 -0.079020                    -0.079020   
4                 -0.016463                    -0.016463   

title  *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
0                           -0.104229  ...    -0.104229     -0.104229   
1                           -0.011781  ...    -0.011781     -0.011781   
2                           -0.009775  ...    -0.009775     -0.009775   
3                           -0.079020  ...    -0.079020     -0.079020   
4                           -0.016463  ...    -0.016463     -0.016463   

title  [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
0          -0.104229                -0.104229   
1          -0.011781                -0.011781   
2          -0.009775                -0.009775   
3          -0.079020                -0.079020   
4          -0.016463                -0.016463   

title  anohana: The Flower We Saw That Day - The Movie (2013)  \
0                                              -0.104229        
1                                              -0.011781        
2                                              -0.009775        
3                                              -0.079020        
4                                              -0.016463        

title  eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
0            -0.104229   -0.104229                       -0.104229   
1            -0.011781   -0.011781                       -0.011781   
2            -0.009775   -0.009775                       -0.009775   
3            -0.079020   -0.079020                       -0.079020   
4            -0.016463   -0.016463                       -0.016463   

title  ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
0                   3.895771                                  -0.104229  
1                  -0.011781                                  -0.011781  
2                  -0.009775                                  -0.009775  
3                  -0.079020                                  -0.079020  
4                  -0.016463                                  -0.016463  

[5 rows x 9719 columns]

In [34]:
U, sigma, Vt = svds(matrix_norm, k =12)

In [35]:
U.shape

(610, 12)

In [36]:
sigma.shape

(12,)

In [37]:
Vt.shape

(12, 9719)

In [38]:
sigma = np.diag(sigma)

In [41]:
svd_user_predict_rating = np.dot(np.dot(U, sigma), Vt) + matrix_1_mean.reshape(-1,1)

In [43]:
df_svd_user_predict_rating = pd.DataFrame(svd_user_predict_rating, columns= matrix.columns)

In [44]:
df_svd_user_predict_rating.shape

(610, 9719)